[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anki-jpn"
description = "This is a set of tooling to allow for generating anki cards for learning/practicing Japanese"
version = "0.0.1"
requires-python = ">= 3.6"
readme = "README.md"
dependencies = [
    "genanki",
    "anki"
]

authors = [
    {name = "Nathan Imse", email = "njimse@gmail.com"}
]
